"""empty message

Revision ID: 0ee25df588ad
Revises: bb2a6797fca4
Create Date: 2020-08-29 17:43:00.259904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ee25df588ad'
down_revision = 'bb2a6797fca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote_activity_manage', 'comment_before_lucky_draw')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote_activity_manage', sa.Column('comment_before_lucky_draw', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='先评论后抽奖或先抽奖再评论'))
    # ### end Alembic commands ###
