"""empty message

Revision ID: 1d21cbaf17b1
Revises: be532c3c438d
Create Date: 2021-01-28 20:14:45.454647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d21cbaf17b1'
down_revision = 'be532c3c438d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_equity',
    sa.Column('equity_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('unit_date', sa.Date(), nullable=False, comment='单位日期'),
    sa.Column('fund_no', sa.String(length=10), nullable=False, comment='基金代码'),
    sa.Column('unit_equity', sa.FLOAT(), nullable=True, comment='单位净值'),
    sa.Column('date_up', sa.FLOAT(), nullable=True, comment='日涨幅'),
    sa.Column('moth_up', sa.FLOAT(), nullable=True, comment='近一个月涨幅'),
    sa.Column('three_moth_up', sa.FLOAT(), nullable=True, comment='近三个月涨幅'),
    sa.Column('six_moth_up', sa.FLOAT(), nullable=True, comment='近六个月涨幅'),
    sa.Column('year_up', sa.FLOAT(), nullable=True, comment='近一年涨幅'),
    sa.Column('three_year_up', sa.FLOAT(), nullable=True, comment='近三年涨幅'),
    sa.Column('total_up', sa.FLOAT(), nullable=True, comment='成立以来的涨幅'),
    sa.Column('total_equity', sa.FLOAT(), nullable=True, comment='累计净值'),
    sa.Column('fund_scale', sa.FLOAT(), nullable=True, comment='基金规模'),
    sa.PrimaryKeyConstraint('equity_id'),
    sa.UniqueConstraint('equity_id'),
    comment='基金净值表'
    )
    op.create_index(op.f('ix_fund_equity_fund_no'), 'fund_equity', ['fund_no'], unique=False)
    op.create_index(op.f('ix_fund_equity_unit_date'), 'fund_equity', ['unit_date'], unique=False)
    op.create_table('fund_info',
    sa.Column('fund_no', sa.String(length=10), autoincrement=False, nullable=False, comment='基金代码'),
    sa.Column('fund_name', sa.String(length=100), nullable=False, comment='基金名称'),
    sa.Column('set_up_date', sa.Date(), nullable=True, comment='成立日期'),
    sa.Column('fund_company', sa.String(length=100), nullable=True, comment='基金公司'),
    sa.Column('fund_manager', sa.String(length=300), nullable=True, comment='基金经理'),
    sa.PrimaryKeyConstraint('fund_no'),
    sa.UniqueConstraint('fund_no'),
    comment='基金表'
    )
    op.create_index(op.f('ix_fund_info_fund_name'), 'fund_info', ['fund_name'], unique=False)
    op.create_table('fund_shares_rel',
    sa.Column('rel_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('fund_no', sa.String(length=10), nullable=False, comment='基金代码'),
    sa.Column('shares_no', sa.String(length=10), nullable=False, comment='股票代码'),
    sa.Column('shares_name', sa.String(length=200), nullable=False, comment='股票名称'),
    sa.Column('now_date', sa.Date(), nullable=False, comment='当前日期'),
    sa.Column('proportion', sa.FLOAT(), nullable=True, comment='持仓占比'),
    sa.Column('up_and_fall', sa.FLOAT(), nullable=True, comment='当日涨跌幅'),
    sa.PrimaryKeyConstraint('rel_id'),
    sa.UniqueConstraint('rel_id'),
    comment='基金股票关系表'
    )
    op.create_index(op.f('ix_fund_shares_rel_fund_no'), 'fund_shares_rel', ['fund_no'], unique=False)
    op.create_index(op.f('ix_fund_shares_rel_now_date'), 'fund_shares_rel', ['now_date'], unique=False)
    op.create_index(op.f('ix_fund_shares_rel_shares_name'), 'fund_shares_rel', ['shares_name'], unique=False)
    op.create_index(op.f('ix_fund_shares_rel_shares_no'), 'fund_shares_rel', ['shares_no'], unique=False)
    op.drop_index('id', table_name='vote_manage')
    op.drop_index('ix_vote_manage_change_by_id', table_name='vote_manage')
    op.drop_index('ix_vote_manage_create_by_id', table_name='vote_manage')
    op.drop_index('ix_vote_manage_deleted_by_id', table_name='vote_manage')
    op.drop_index('ix_vote_manage_state', table_name='vote_manage')
    op.drop_index('ix_vote_manage_temp_name', table_name='vote_manage')
    op.drop_table('vote_manage')
    op.add_column('vote_activity', sa.Column('background_img', sa.String(length=300), nullable=False, comment='活动底图图片链接'))
    op.drop_column('vote_activity', 'show_type')
    op.drop_column('vote_activity', 'template')
    op.drop_column('vote_activity', 'show_ranking_list')
    op.create_table_comment(
        'wechat_subscriber',
        '微信订阅者表',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'wechat_subscriber',
        existing_comment='微信订阅者表',
        schema=None
    )
    op.add_column('vote_activity', sa.Column('show_ranking_list', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否显示排行榜，默认显示'))
    op.add_column('vote_activity', sa.Column('template', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False, comment='活动模板'))
    op.add_column('vote_activity', sa.Column('show_type', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='投票显示设置，默认宫格'))
    op.drop_column('vote_activity', 'background_img')
    op.create_table('vote_manage',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False, comment='主键ID'),
    sa.Column('state', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='状态值, 0为已删除, 1为正常, 2为锁定'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('create_by_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='创建者ID'),
    sa.Column('last_change_time', mysql.DATETIME(), nullable=True, comment='最后修改的时间'),
    sa.Column('change_by_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='最后修改者ID'),
    sa.Column('deleted_time', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='删除者id'),
    sa.Column('temp_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='模板名称'),
    sa.Column('temp_img', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300), nullable=False, comment='模板背景图片链接'),
    sa.Column('posters_img', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300), nullable=False, comment='模板海报图片链接'),
    sa.PrimaryKeyConstraint('id'),
    comment='投票模板表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='投票模板表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_vote_manage_temp_name', 'vote_manage', ['temp_name'], unique=False)
    op.create_index('ix_vote_manage_state', 'vote_manage', ['state'], unique=False)
    op.create_index('ix_vote_manage_deleted_by_id', 'vote_manage', ['deleted_by_id'], unique=False)
    op.create_index('ix_vote_manage_create_by_id', 'vote_manage', ['create_by_id'], unique=False)
    op.create_index('ix_vote_manage_change_by_id', 'vote_manage', ['change_by_id'], unique=False)
    op.create_index('id', 'vote_manage', ['id'], unique=True)
    op.drop_index(op.f('ix_fund_shares_rel_shares_no'), table_name='fund_shares_rel')
    op.drop_index(op.f('ix_fund_shares_rel_shares_name'), table_name='fund_shares_rel')
    op.drop_index(op.f('ix_fund_shares_rel_now_date'), table_name='fund_shares_rel')
    op.drop_index(op.f('ix_fund_shares_rel_fund_no'), table_name='fund_shares_rel')
    op.drop_table('fund_shares_rel')
    op.drop_index(op.f('ix_fund_info_fund_name'), table_name='fund_info')
    op.drop_table('fund_info')
    op.drop_index(op.f('ix_fund_equity_unit_date'), table_name='fund_equity')
    op.drop_index(op.f('ix_fund_equity_fund_no'), table_name='fund_equity')
    op.drop_table('fund_equity')
    # ### end Alembic commands ###
