"""empty message

Revision ID: 24c4974b2941
Revises: 38e41ffc7f1d
Create Date: 2020-08-23 17:37:06.714852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24c4974b2941'
down_revision = '38e41ffc7f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote_activity_manage', sa.Column('end_date', sa.Date(), nullable=False, comment='活动结束日期'))
    op.add_column('vote_activity_manage', sa.Column('start_date', sa.Date(), nullable=False, comment='活动开始日期'))
    op.alter_column('vote_activity_manage', 'lottery_limit',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否限制抽奖',
               existing_comment='是否限制',
               existing_nullable=True)
    op.drop_column('vote_activity_manage', 'end_data')
    op.drop_column('vote_activity_manage', 'start_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote_activity_manage', sa.Column('start_data', sa.DATE(), nullable=False, comment='活动开始日期'))
    op.add_column('vote_activity_manage', sa.Column('end_data', sa.DATE(), nullable=False, comment='活动结束日期'))
    op.alter_column('vote_activity_manage', 'lottery_limit',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否限制',
               existing_comment='是否限制抽奖',
               existing_nullable=True)
    op.drop_column('vote_activity_manage', 'start_date')
    op.drop_column('vote_activity_manage', 'end_date')
    # ### end Alembic commands ###
