"""empty message

Revision ID: 4135562963db
Revises: 0ee25df588ad
Create Date: 2020-09-19 17:07:41.400926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4135562963db'
down_revision = '0ee25df588ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_operation_log', sa.Column('name', sa.String(length=200), nullable=True, comment='操作名称'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_operation_log', 'name')
    # ### end Alembic commands ###
