"""empty message

Revision ID: 57f113fa2fba
Revises: a7ff1ba264ec
Create Date: 2021-02-04 19:03:21.589572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57f113fa2fba'
down_revision = 'a7ff1ba264ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fund_shares_rel', 'hold_num',
               existing_type=mysql.FLOAT(),
               comment='持股数量（股）',
               existing_comment='持股数量(万股)',
               existing_nullable=True)
    op.alter_column('fund_shares_rel', 'hold_price',
               existing_type=mysql.FLOAT(),
               comment='持股金额（元）',
               existing_comment='持股金额(亿元)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fund_shares_rel', 'hold_price',
               existing_type=mysql.FLOAT(),
               comment='持股金额(亿元)',
               existing_comment='持股金额（元）',
               existing_nullable=True)
    op.alter_column('fund_shares_rel', 'hold_num',
               existing_type=mysql.FLOAT(),
               comment='持股数量(万股)',
               existing_comment='持股数量（股）',
               existing_nullable=True)
    # ### end Alembic commands ###
