"""empty message

Revision ID: 59a3c1b46e45
Revises: 1d21cbaf17b1
Create Date: 2021-02-03 14:43:46.329891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59a3c1b46e45'
down_revision = '1d21cbaf17b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_shares_rel', sa.Column('hold_change', sa.FLOAT(), nullable=True, comment='持有变化, 0：不变, 整数：增持, 负数：减持'))
    op.alter_column('fund_shares_rel', 'proportion',
               existing_type=mysql.FLOAT(),
               comment='当前持仓占比',
               existing_comment='持仓占比',
               existing_nullable=True)
    op.drop_index('ix_fund_shares_rel_now_date', table_name='fund_shares_rel')
    op.drop_index('ix_fund_shares_rel_shares_name', table_name='fund_shares_rel')
    op.drop_column('fund_shares_rel', 'up_and_fall')
    op.drop_column('fund_shares_rel', 'now_date')
    op.drop_column('fund_shares_rel', 'shares_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_shares_rel', sa.Column('shares_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=200), nullable=False, comment='股票名称'))
    op.add_column('fund_shares_rel', sa.Column('now_date', sa.DATE(), nullable=False, comment='当前日期'))
    op.add_column('fund_shares_rel', sa.Column('up_and_fall', mysql.FLOAT(), nullable=True, comment='当日涨跌幅'))
    op.create_index('ix_fund_shares_rel_shares_name', 'fund_shares_rel', ['shares_name'], unique=False)
    op.create_index('ix_fund_shares_rel_now_date', 'fund_shares_rel', ['now_date'], unique=False)
    op.alter_column('fund_shares_rel', 'proportion',
               existing_type=mysql.FLOAT(),
               comment='持仓占比',
               existing_comment='当前持仓占比',
               existing_nullable=True)
    op.drop_column('fund_shares_rel', 'hold_change')
    # ### end Alembic commands ###
