"""empty message

Revision ID: 69ec475763f6
Revises: 1d4aed2f56a3
Create Date: 2020-08-23 23:46:52.564444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69ec475763f6'
down_revision = '1d4aed2f56a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote_activity_manage', 'vote_activity_type',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='投票后的游戏, 0为没有活动, 1为幸运大转盘, 2为幸运九宫格, 3为幸福刮刮乐, 4为答题有奖, 5为玩游戏有奖',
               existing_comment='投票后的游戏, 0为没有活动, 1为大转盘抽奖, 2为九宫格抽奖, 3为刮刮乐抽奖, 4为答题有奖, 5为玩游戏有奖',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote_activity_manage', 'vote_activity_type',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='投票后的游戏, 0为没有活动, 1为大转盘抽奖, 2为九宫格抽奖, 3为刮刮乐抽奖, 4为答题有奖, 5为玩游戏有奖',
               existing_comment='投票后的游戏, 0为没有活动, 1为幸运大转盘, 2为幸运九宫格, 3为幸福刮刮乐, 4为答题有奖, 5为玩游戏有奖',
               existing_nullable=True)
    # ### end Alembic commands ###
