"""empty message

Revision ID: 8a6ec38d52ce
Revises: a2cf769539cf
Create Date: 2020-09-29 11:15:14.996778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a6ec38d52ce'
down_revision = 'a2cf769539cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='sys_user_role_rel')
    op.drop_index('ix_sys_user_role_rel_change_by_id', table_name='sys_user_role_rel')
    op.drop_index('ix_sys_user_role_rel_create_by_id', table_name='sys_user_role_rel')
    op.drop_index('ix_sys_user_role_rel_deleted_by_id', table_name='sys_user_role_rel')
    op.drop_index('ix_sys_user_role_rel_role_id', table_name='sys_user_role_rel')
    op.drop_index('ix_sys_user_role_rel_state', table_name='sys_user_role_rel')
    op.drop_index('ix_sys_user_role_rel_user_id', table_name='sys_user_role_rel')
    op.drop_table('sys_user_role_rel')
    op.drop_column('sys_department', 'department_code')
    op.alter_column('sys_menu', 'menu_code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               comment='组件路径(前端请求文件的路径里),目录可填Layout',
               existing_comment='前端请求文件的路径里,@views后的路径或填Layout',
               existing_nullable=False)
    op.alter_column('sys_menu', 'menu_type',
               existing_type=mysql.SMALLINT(),
               comment='资源类型,0为目录、1为菜单、2为按钮',
               existing_comment='资源类型,1为菜单、2为按钮、3为动作',
               existing_nullable=True)
    op.alter_column('sys_menu', 'menu_url',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               comment='请求地址,即访问后台接口的url',
               existing_comment='菜单url,即访问后台接口的url',
               existing_nullable=False)
    op.alter_column('sys_role', 'data_permission_type',
               existing_type=mysql.SMALLINT(),
               comment='数据权限,0仅自己参与过的数据,1本部门的权限, 2本部门及所有子部门权限，3表示全部权限,4自定义权限',
               existing_comment='数据权限(可以查看什么部门的数据),0仅自己参与过的数据,1本部门的权限, 2本部门及所有子部门权限，3表示全部权限,4自定义权限',
               existing_nullable=False)
    op.add_column('sys_user', sa.Column('remarks', sa.String(length=200), nullable=True, comment='备注说明'))
    op.add_column('sys_user', sa.Column('role_id', sa.String(length=20), nullable=True, comment='角色id'))
    op.create_index(op.f('ix_sys_user_role_id'), 'sys_user', ['role_id'], unique=False)
    op.drop_column('sys_user', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_user', sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否超级管理员'))
    op.drop_index(op.f('ix_sys_user_role_id'), table_name='sys_user')
    op.drop_column('sys_user', 'role_id')
    op.drop_column('sys_user', 'remarks')
    op.alter_column('sys_role', 'data_permission_type',
               existing_type=mysql.SMALLINT(),
               comment='数据权限(可以查看什么部门的数据),0仅自己参与过的数据,1本部门的权限, 2本部门及所有子部门权限，3表示全部权限,4自定义权限',
               existing_comment='数据权限,0仅自己参与过的数据,1本部门的权限, 2本部门及所有子部门权限，3表示全部权限,4自定义权限',
               existing_nullable=False)
    op.alter_column('sys_menu', 'menu_url',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               comment='菜单url,即访问后台接口的url',
               existing_comment='请求地址,即访问后台接口的url',
               existing_nullable=False)
    op.alter_column('sys_menu', 'menu_type',
               existing_type=mysql.SMALLINT(),
               comment='资源类型,1为菜单、2为按钮、3为动作',
               existing_comment='资源类型,0为目录、1为菜单、2为按钮',
               existing_nullable=True)
    op.alter_column('sys_menu', 'menu_code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               comment='前端请求文件的路径里,@views后的路径或填Layout',
               existing_comment='组件路径(前端请求文件的路径里),目录可填Layout',
               existing_nullable=False)
    op.add_column('sys_department', sa.Column('department_code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=15), nullable=False, comment='部门编号'))
    op.create_table('sys_user_role_rel',
    sa.Column('id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20), nullable=False, comment='主键ID'),
    sa.Column('state', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='状态值, 0为已删除, 1为正常, 2为锁定'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('create_by_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='创建者ID'),
    sa.Column('last_change_time', mysql.DATETIME(), nullable=True, comment='最后修改的时间'),
    sa.Column('change_by_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='最后修改者ID'),
    sa.Column('deleted_time', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='删除者id'),
    sa.Column('user_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='用户id'),
    sa.Column('role_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='角色id'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户角色表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='用户角色表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_sys_user_role_rel_user_id', 'sys_user_role_rel', ['user_id'], unique=False)
    op.create_index('ix_sys_user_role_rel_state', 'sys_user_role_rel', ['state'], unique=False)
    op.create_index('ix_sys_user_role_rel_role_id', 'sys_user_role_rel', ['role_id'], unique=False)
    op.create_index('ix_sys_user_role_rel_deleted_by_id', 'sys_user_role_rel', ['deleted_by_id'], unique=False)
    op.create_index('ix_sys_user_role_rel_create_by_id', 'sys_user_role_rel', ['create_by_id'], unique=False)
    op.create_index('ix_sys_user_role_rel_change_by_id', 'sys_user_role_rel', ['change_by_id'], unique=False)
    op.create_index('id', 'sys_user_role_rel', ['id'], unique=True)
    # ### end Alembic commands ###
