"""empty message

Revision ID: 9116555f981b
Revises: 57f113fa2fba
Create Date: 2021-02-09 01:28:25.382071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9116555f981b'
down_revision = '57f113fa2fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
