"""empty message

Revision ID: a2cf769539cf
Revises: 4135562963db
Create Date: 2020-09-21 09:53:21.091245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2cf769539cf'
down_revision = '4135562963db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_user', sa.Column('is_admin', sa.Boolean(), nullable=True, comment='是否超级管理员'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_user', 'is_admin')
    # ### end Alembic commands ###
