"""empty message

Revision ID: a7ff1ba264ec
Revises: f9e232f4e919
Create Date: 2021-02-04 18:55:36.842990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ff1ba264ec'
down_revision = 'f9e232f4e919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_shares_rel', sa.Column('hold_num', sa.FLOAT(), nullable=True, comment='持股数量(万股)'))
    op.add_column('fund_shares_rel', sa.Column('hold_price', sa.FLOAT(), nullable=True, comment='持股金额(亿元)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fund_shares_rel', 'hold_price')
    op.drop_column('fund_shares_rel', 'hold_num')
    # ### end Alembic commands ###
