"""empty message

Revision ID: bb2a6797fca4
Revises: 16d5c817baf4
Create Date: 2020-08-29 16:42:58.020867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb2a6797fca4'
down_revision = '16d5c817baf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sys_department_parent_ids', table_name='sys_department')
    op.drop_column('sys_department', 'parent_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_department', sa.Column('parent_ids', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='部门父级ids'))
    op.create_index('ix_sys_department_parent_ids', 'sys_department', ['parent_ids'], unique=False)
    # ### end Alembic commands ###
