"""empty message

Revision ID: f9e232f4e919
Revises: 2c69acde2f0b
Create Date: 2021-02-04 17:24:39.015820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e232f4e919'
down_revision = '2c69acde2f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_shares_rel', sa.Column('unit_date', sa.Date(), nullable=False, comment='更新日期'))
    op.create_index(op.f('ix_fund_shares_rel_unit_date'), 'fund_shares_rel', ['unit_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_shares_rel_unit_date'), table_name='fund_shares_rel')
    op.drop_column('fund_shares_rel', 'unit_date')
    # ### end Alembic commands ###
